'use client';

import {
  Badge,
  Button,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  EmptyState,
  Input,
  Label,
  LoadingSpinner,
} from '@dripplex/ui';
import * as React from 'react';

import type {
  BankAccountDto,
  RedemptionCodePreviewDto,
  StoreRedemptionResultDto,
  BankOptionDto,
  ResolvedBankAccountDto,
  WithdrawalRequestDto,
  CommissionAccountDto,
  CommissionLedgerEntryDto,
  OrderSettlementDto,
  OrderSettlementStatus,
  WalletDto,
  WalletLedgerEntryDto,
} from '@dripplex/types';

import { describeSdkError, sdk } from '@/lib/sdk';

const SETTLEMENTS_PAGE_SIZE = 10;
const LEDGER_PAGE_SIZE = 10;
const COMMERCIAL_LEDGER_PAGE_SIZE = 10;

const COMMISSION_ENTRY_TYPE_LABEL: Record<CommissionLedgerEntryDto['type'], string> = {
  ACCRUAL: 'Commission accrued',
  PAYMENT: 'Payment recorded',
  ADJUSTMENT: 'Adjustment',
};

// The backend's OrderSettlementStatus has exactly four values. PENDING
// only exists transiently between wallet credit and the audit write —
// see MerchantSettlementService.settleOrder — but is included here for
// completeness rather than assumed away.
const SETTLEMENT_STATUS_LABEL: Record<OrderSettlementStatus, string> = {
  PENDING: 'Processing',
  COMPLETED: 'Settled',
  FAILED: 'Failed',
  REVERSED: 'Reversed',
};

const SETTLEMENT_STATUS_BADGE_VARIANT: Record<
  OrderSettlementStatus,
  'outline' | 'accent' | 'success'
> = {
  PENDING: 'accent',
  COMPLETED: 'success',
  FAILED: 'outline',
  REVERSED: 'outline',
};

function formatMoney(amount: number, currency: string): string {
  return new Intl.NumberFormat('en-NG', { style: 'currency', currency }).format(amount);
}

function formatDate(iso: string): string {
  return new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium', timeStyle: 'short' }).format(
    new Date(iso),
  );
}

function formatPercent(rate: number): string {
  return new Intl.NumberFormat('en-NG', { style: 'percent', maximumFractionDigits: 1 }).format(
    rate,
  );
}

export default function WalletPage(): React.JSX.Element {
  const [wallet, setWallet] = React.useState<WalletDto | null>(null);
  const [walletLoading, setWalletLoading] = React.useState(true);
  const [walletError, setWalletError] = React.useState<string | null>(null);

  const loadWallet = React.useCallback(async () => {
    try {
      const data = await sdk.merchant.getWallet();
      setWallet(data);
      setWalletError(null);
    } catch (error) {
      setWalletError(describeSdkError(error).description);
    } finally {
      setWalletLoading(false);
    }
  }, []);

  React.useEffect(() => {
    void loadWallet();
    // Settlements and the wallet balance both change the moment an order
    // completes — same 15s live-data precedent Incoming Orders uses,
    // since there is no wallet-domain websocket push in this codebase.
    const interval = setInterval(() => {
      void loadWallet();
    }, 15_000);
    return () => {
      clearInterval(interval);
    };
  }, [loadWallet]);

  return (
    <div className="mx-auto flex w-full max-w-4xl flex-col gap-6">
      <div>
        <h1 className="font-display text-3xl font-semibold tracking-tight">Wallet &amp; Bank</h1>
        <p className="text-muted-foreground mt-2 text-sm">
          Your DrippleX wallet balance, every settlement breakdown, and the bank account your
          settlements pay out to.
        </p>
      </div>

      {walletError ? (
        <p className="text-destructive text-sm" role="alert">
          {walletError}
        </p>
      ) : null}

      {walletLoading ? (
        <div className="flex justify-center py-12">
          <LoadingSpinner />
        </div>
      ) : (
        <>
          <BalanceCard wallet={wallet} />
          <RedeemPointsCard
            currency={wallet?.currency ?? 'NGN'}
            onRedeemed={() => {
              void loadWallet();
            }}
          />
          <PayoutCard wallet={wallet} />
          <CommercialCard
            currency={wallet?.currency ?? 'NGN'}
            wallet={wallet}
            onSettled={() => {
              void loadWallet();
            }}
          />
          <SettlementsCard />
          <LedgerCard currency={wallet?.currency ?? 'NGN'} />
          <CommercialLedgerCard currency={wallet?.currency ?? 'NGN'} />
          <BankAccountsCard />
        </>
      )}
    </div>
  );
}

/**
 * DPX-LOYALTY-002 — taking a customer's DX points at the counter.
 *
 * Two steps on purpose. The merchant types the code and sees what it is worth
 * and whose it is *before* accepting it; finding out after handing over goods
 * that a code was worth ₦2 rather than ₦200 is the merchant's loss, and the
 * check costs one call. Nothing moves until Confirm.
 *
 * The code is generated by the holder in their own app and expires in ten
 * minutes. There is deliberately no "look the customer up by phone" — that
 * would let anyone who knows a phone number spend that person's balance.
 */
function RedeemPointsCard({
  currency,
  onRedeemed,
}: {
  currency: string;
  onRedeemed: () => void;
}): React.JSX.Element {
  const [code, setCode] = React.useState('');
  const [preview, setPreview] = React.useState<RedemptionCodePreviewDto | null>(null);
  const [result, setResult] = React.useState<StoreRedemptionResultDto | null>(null);
  const [error, setError] = React.useState<string | null>(null);
  const [busy, setBusy] = React.useState(false);

  function reset(): void {
    setCode('');
    setPreview(null);
    setError(null);
  }

  async function check(): Promise<void> {
    setBusy(true);
    setError(null);
    setResult(null);
    try {
      setPreview(await sdk.loyalty.preview({ code: code.trim() }));
    } catch (checkError) {
      setPreview(null);
      setError(describeSdkError(checkError).description);
    } finally {
      setBusy(false);
    }
  }

  async function confirm(): Promise<void> {
    setBusy(true);
    setError(null);
    try {
      const redeemed = await sdk.loyalty.redeem({ code: code.trim() });
      setResult(redeemed);
      reset();
      onRedeemed();
    } catch (confirmError) {
      setError(describeSdkError(confirmError).description);
    } finally {
      setBusy(false);
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Redeem DX points</CardTitle>
        <p className="text-muted-foreground text-sm">
          A customer, driver or rider can pay with DX points in your store. Ask them to generate a
          code in their DrippleX app, type it in below, and the value lands in your wallet.
        </p>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <div className="flex flex-wrap items-end gap-3">
          <div className="min-w-[200px] flex-1">
            <Label htmlFor="dx-points-code">Customer&apos;s code</Label>
            <Input
              id="dx-points-code"
              value={code}
              autoComplete="off"
              spellCheck={false}
              placeholder="e.g. 7KQD2MXR"
              onChange={(event) => {
                setCode(event.target.value.toUpperCase());
                setPreview(null);
                setError(null);
              }}
            />
          </div>
          <Button
            onClick={() => {
              void check();
            }}
            disabled={code.trim() === '' || busy || preview !== null}
          >
            {busy && preview === null ? 'Checking…' : 'Check code'}
          </Button>
        </div>

        {error ? (
          <p className="text-destructive text-sm" role="alert">
            {error}
          </p>
        ) : null}

        {preview ? (
          <div className="bg-muted/40 flex flex-col gap-3 rounded-lg border px-4 py-3">
            <div className="flex flex-wrap items-baseline gap-x-8 gap-y-2">
              <div>
                <p className="text-muted-foreground text-xs">You will be credited</p>
                <p className="font-display text-2xl font-semibold tracking-tight">
                  {formatMoney(preview.amount, currency)}
                </p>
              </div>
              <div>
                <p className="text-muted-foreground text-xs">Points</p>
                <p className="text-lg font-medium">{preview.points.toLocaleString('en-NG')}</p>
              </div>
              <div>
                <p className="text-muted-foreground text-xs">Customer</p>
                <p className="text-lg font-medium">{preview.holderName}</p>
              </div>
            </div>
            <div className="flex gap-3">
              <Button
                onClick={() => {
                  void confirm();
                }}
                disabled={busy}
              >
                {busy ? 'Redeeming…' : `Confirm ${formatMoney(preview.amount, currency)}`}
              </Button>
              <Button variant="secondary" onClick={reset} disabled={busy}>
                Cancel
              </Button>
            </div>
            <p className="text-muted-foreground text-xs">
              Code expires {formatDate(preview.expiresAt)}. Nothing moves until you confirm.
            </p>
          </div>
        ) : null}

        {result ? (
          <p className="rounded-lg border border-emerald-500/40 bg-emerald-500/5 px-3 py-2 text-sm text-emerald-700">
            {formatMoney(result.amount, currency)} added to your wallet from {result.holderName}
            &apos;s {result.points.toLocaleString('en-NG')} DX points.
          </p>
        ) : null}
      </CardContent>
    </Card>
  );
}

function BalanceCard({ wallet }: { wallet: WalletDto | null }): React.JSX.Element {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Current balance</CardTitle>
      </CardHeader>
      <CardContent>
        {wallet ? (
          <div className="flex flex-wrap items-baseline gap-x-8 gap-y-3">
            <div>
              <p className="text-muted-foreground text-xs">Available</p>
              <p className="font-display text-3xl font-semibold tracking-tight">
                {formatMoney(wallet.availableBalance, wallet.currency)}
              </p>
            </div>
            {wallet.pendingBalance > 0 ? (
              <div>
                <p className="text-muted-foreground text-xs">Pending</p>
                <p className="text-lg font-medium">
                  {formatMoney(wallet.pendingBalance, wallet.currency)}
                </p>
              </div>
            ) : null}
          </div>
        ) : (
          <p className="text-muted-foreground text-sm">
            No wallet yet — it is created automatically once your first order settles.
          </p>
        )}
      </CardContent>
    </Card>
  );
}

/**
 * DPX-COMMERCIAL-001 Slice 5 — surfaces the commission credit engine
 * (Slices 1-4) that already governs mode-B/mode-C settlements: outstanding
 * commission, credit limit, available credit, status, and the blocked
 * warning. Pure read — no new commercial behavior, matches
 * `MerchantCommercialController`'s `GET /merchant/commercial/account` 1:1.
 */
/**
 * Asking to be paid out of the wallet balance.
 *
 * Automatic settlement is unchanged and remains how a merchant is normally
 * paid — an online order completing transfers the net amount to the verified
 * account without anybody asking. This is the manual request alongside it, for
 * the balance automatic settlement does not move, and it goes into the same
 * Operations queue and the same approval as a driver's or a rider's.
 *
 * The destination is the verified settlement account already on file. It is
 * not chosen here, because a second bank account linked only for payouts is
 * one more record nobody keeps in step with the first.
 */
function PayoutCard({ wallet }: { wallet: WalletDto | null }): React.JSX.Element {
  const [accounts, setAccounts] = React.useState<BankAccountDto[]>([]);
  const [payouts, setPayouts] = React.useState<WithdrawalRequestDto[]>([]);
  const [pinSet, setPinSet] = React.useState<boolean | null>(null);
  const [amount, setAmount] = React.useState('');
  const [pin, setPin] = React.useState('');
  const [busy, setBusy] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [notice, setNotice] = React.useState<string | null>(null);

  const load = React.useCallback(() => {
    void sdk.merchant
      .listBankAccounts()
      .then(setAccounts)
      .catch(() => {
        setAccounts([]);
      });
    void sdk.merchant
      .listPayouts()
      .then((page) => {
        setPayouts(page.items);
      })
      .catch(() => {
        setPayouts([]);
      });
    void sdk.merchant
      .hasWalletPin()
      .then((r) => {
        setPinSet(r.set);
      })
      .catch(() => {
        setPinSet(null);
      });
  }, []);
  React.useEffect(load, [load]);

  const destination = accounts.find((a) => a.isDefault && a.verifiedAt !== null);
  const available = wallet?.availableBalance ?? 0;
  const requested = Number(amount);
  const canRequest =
    destination !== undefined &&
    pinSet === true &&
    Number.isFinite(requested) &&
    requested > 0 &&
    requested <= available &&
    /^[0-9]{4}$/.test(pin);

  const submit = (): void => {
    // canRequest already establishes a verified destination; TypeScript narrows
    // `destination` through it, so re-checking here is dead code.
    if (!canRequest) {
      return;
    }
    setBusy(true);
    setError(null);
    setNotice(null);
    void (async () => {
      try {
        const result = await sdk.merchant.requestPayout({
          amount: requested,
          bankAccountId: destination.id,
          pin,
        });
        setNotice(
          result.payout === null
            ? 'That amount cleared commission owed, so there is nothing to transfer.'
            : 'Payout requested. Operations will action it on the next run.',
        );
        setAmount('');
        setPin('');
        load();
      } catch (submitError) {
        setError(describeSdkError(submitError).description);
      } finally {
        setBusy(false);
      }
    })();
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Request a payout</CardTitle>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <p className="text-muted-foreground text-sm">
          Online orders settle to your bank automatically. Use this for the balance that has not
          settled on its own — Operations approves it the same way they do for drivers and riders.
        </p>

        {destination === undefined ? (
          <p className="text-muted-foreground text-sm">
            Add a bank account above and confirm it with your bank first. A payout only goes to a
            verified default account.
          </p>
        ) : (
          <>
            <p className="text-sm">
              To <span className="font-medium">{destination.bankName}</span> ·{' '}
              {destination.accountName} · {destination.accountNumber}
            </p>

            {pinSet === false ? (
              <p className="text-muted-foreground text-sm">
                Set a 4-digit wallet PIN before requesting a payout.
              </p>
            ) : null}

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="payoutAmount">Amount</Label>
                <Input
                  id="payoutAmount"
                  inputMode="decimal"
                  value={amount}
                  onChange={(event) => {
                    setAmount(event.target.value.replace(/[^0-9.]/g, ''));
                  }}
                />
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="payoutPin">Wallet PIN</Label>
                <Input
                  id="payoutPin"
                  inputMode="numeric"
                  maxLength={4}
                  value={pin}
                  onChange={(event) => {
                    setPin(event.target.value.replace(/[^0-9]/g, ''));
                  }}
                />
              </div>
              <div className="flex items-end">
                <Button type="button" disabled={!canRequest || busy} onClick={submit}>
                  {busy ? 'Requesting…' : 'Request payout'}
                </Button>
              </div>
            </div>
          </>
        )}

        {error !== null ? (
          <p className="text-destructive text-sm" role="alert">
            {error}
          </p>
        ) : null}
        {notice !== null ? <p className="text-sm">{notice}</p> : null}

        {payouts.length > 0 ? (
          <div className="flex flex-col gap-2">
            <p className="text-muted-foreground text-xs">Recent requests</p>
            {payouts.slice(0, 5).map((payout) => (
              <div key={payout.id} className="flex items-center justify-between text-sm">
                <span>{formatMoney(payout.amount, payout.currency)}</span>
                <span className="text-muted-foreground">{payout.status}</span>
              </div>
            ))}
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}

function CommercialCard({
  currency,
  wallet,
  onSettled,
}: {
  currency: string;
  wallet: WalletDto | null;
  onSettled: () => void;
}): React.JSX.Element | null {
  const [account, setAccount] = React.useState<CommissionAccountDto | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);
  const [settling, setSettling] = React.useState(false);
  const [settleError, setSettleError] = React.useState<string | null>(null);
  const [settled, setSettled] = React.useState<number | null>(null);

  const load = React.useCallback(async () => {
    try {
      const data = await sdk.commercial.getAccount();
      setAccount(data);
      setError(null);
    } catch (loadError) {
      setError(describeSdkError(loadError).description);
    } finally {
      setLoading(false);
    }
  }, []);

  React.useEffect(() => {
    void load();
  }, [load]);

  if (loading) {
    return null;
  }

  const availableCredit = account
    ? Math.max(0, account.creditLimit - account.outstandingBalance)
    : 0;
  // Offer whichever is smaller — the debt, or what is actually in the wallet.
  // Offering the full debt when the balance cannot cover it turns a button into
  // an error message.
  const payable = Number(
    Math.min(account?.outstandingBalance ?? 0, wallet?.availableBalance ?? 0).toFixed(2),
  );

  async function settle(): Promise<void> {
    if (payable <= 0) return;
    setSettling(true);
    setSettleError(null);
    try {
      const outcome = await sdk.wallet.settleMerchantCommission({ amount: payable });
      setSettled(outcome.settled);
      setAccount((current) =>
        current === null ? current : { ...current, outstandingBalance: outcome.outstandingBalance },
      );
      onSettled();
    } catch (settleFailure) {
      setSettleError(describeSdkError(settleFailure).description);
    } finally {
      setSettling(false);
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Commission owed</CardTitle>
        <p className="text-muted-foreground text-sm">
          Commission owed on Pay-to-Merchant and Cash-on-Delivery orders — settled directly with you
          rather than deducted before payout, so it accrues here instead.
        </p>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        {error ? (
          <p className="text-destructive text-sm" role="alert">
            {error}
          </p>
        ) : null}

        {account ? (
          <>
            {account.blocked ? (
              <p className="border-destructive/40 bg-destructive/5 text-destructive rounded-lg border px-3 py-2 text-sm">
                Your outstanding commission has exceeded your credit limit. New orders may be
                affected until this is paid down.
              </p>
            ) : null}
            <div className="flex flex-wrap items-baseline gap-x-8 gap-y-3">
              <div>
                <p className="text-muted-foreground text-xs">Outstanding commission</p>
                <p className="font-display text-2xl font-semibold tracking-tight">
                  {formatMoney(account.outstandingBalance, currency)}
                </p>
              </div>
              <div>
                <p className="text-muted-foreground text-xs">Credit limit</p>
                <p className="text-lg font-medium">{formatMoney(account.creditLimit, currency)}</p>
              </div>
              <div>
                <p className="text-muted-foreground text-xs">Available credit</p>
                <p className="text-lg font-medium">{formatMoney(availableCredit, currency)}</p>
              </div>
              <div>
                <p className="text-muted-foreground text-xs">Status</p>
                <Badge variant={account.blocked ? 'outline' : 'success'}>
                  {account.blocked
                    ? 'Blocked'
                    : account.outstandingBalance > 0
                      ? 'Outstanding'
                      : 'Clear'}
                </Badge>
              </div>
            </div>
          </>
        ) : (
          <p className="text-muted-foreground text-sm">
            No commission owed yet — nothing accrues until a Pay-to-Merchant or Cash-on-Delivery
            order settles.
          </p>
        )}

        {account !== null && account.outstandingBalance > 0 ? (
          <div className="flex flex-col gap-2 border-t pt-4">
            <p className="text-muted-foreground text-sm">
              You can clear this from your wallet balance instead of waiting — useful for value
              earned by redeeming DX points in store. Never takes more than is owed.
            </p>
            {settleError ? (
              <p className="text-destructive text-sm" role="alert">
                {settleError}
              </p>
            ) : null}
            {settled !== null ? (
              <p className="text-sm text-emerald-700">
                {formatMoney(settled, currency)} paid off your commission.
              </p>
            ) : null}
            <div>
              <Button
                variant="secondary"
                disabled={settling || payable <= 0}
                onClick={() => {
                  void settle();
                }}
              >
                {settling
                  ? 'Paying…'
                  : payable <= 0
                    ? 'Not enough wallet balance'
                    : `Pay ${formatMoney(payable, currency)} from wallet`}
              </Button>
            </div>
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}

function SettlementsCard(): React.JSX.Element {
  const [items, setItems] = React.useState<OrderSettlementDto[]>([]);
  const [page, setPage] = React.useState(1);
  const [totalPages, setTotalPages] = React.useState(1);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);

  const load = React.useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await sdk.merchant.listSettlements({ page, pageSize: SETTLEMENTS_PAGE_SIZE });
      setItems(result.items);
      setTotalPages(result.meta.totalPages);
    } catch (loadError) {
      setError(describeSdkError(loadError).description);
    } finally {
      setLoading(false);
    }
  }, [page]);

  React.useEffect(() => {
    void load();
  }, [load]);

  return (
    <Card>
      <CardHeader>
        <CardTitle>Settlements</CardTitle>
        <p className="text-muted-foreground text-sm">
          Every completed order, broken down from the sale price down to what was paid into your
          wallet.
        </p>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        {error ? (
          <p className="text-destructive text-sm" role="alert">
            {error}
          </p>
        ) : null}

        {loading && items.length === 0 ? (
          <div className="flex justify-center py-8">
            <LoadingSpinner />
          </div>
        ) : items.length === 0 ? (
          <EmptyState
            title="No settlements yet"
            description="A settlement is created here the moment an order you fulfil is marked complete."
          />
        ) : (
          <div className="border-border/70 divide-border/70 divide-y overflow-hidden rounded-lg border">
            {items.map((settlement) => (
              <div key={settlement.id} className="flex flex-col gap-2 px-4 py-3">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <p className="text-sm font-medium">Order {settlement.orderNumber}</p>
                    <Badge variant={SETTLEMENT_STATUS_BADGE_VARIANT[settlement.status]}>
                      {SETTLEMENT_STATUS_LABEL[settlement.status]}
                    </Badge>
                  </div>
                  <p className="text-muted-foreground text-xs">
                    {formatDate(settlement.createdAt)}
                  </p>
                </div>
                <dl className="grid grid-cols-2 gap-x-4 gap-y-1 text-sm sm:grid-cols-4">
                  <div>
                    <dt className="text-muted-foreground text-xs">Gross (subtotal)</dt>
                    <dd>{formatMoney(settlement.grossAmount, settlement.currency)}</dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground text-xs">
                      Commission ({formatPercent(settlement.commissionRate)})
                    </dt>
                    <dd className="text-destructive">
                      -{formatMoney(settlement.commissionAmount, settlement.currency)}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground text-xs">You received</dt>
                    <dd className="font-semibold">
                      {formatMoney(settlement.merchantAmount, settlement.currency)}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground text-xs">Status</dt>
                    <dd>
                      {settlement.status === 'FAILED' && settlement.failureReason
                        ? settlement.failureReason
                        : settlement.status === 'REVERSED' && settlement.reversalReason
                          ? `Reversed: ${settlement.reversalReason}`
                          : SETTLEMENT_STATUS_LABEL[settlement.status]}
                    </dd>
                  </div>
                </dl>
              </div>
            ))}
          </div>
        )}

        <Pagination page={page} totalPages={totalPages} onChange={setPage} />
      </CardContent>
    </Card>
  );
}

function LedgerCard({ currency }: { currency: string }): React.JSX.Element {
  const [items, setItems] = React.useState<WalletLedgerEntryDto[]>([]);
  const [page, setPage] = React.useState(1);
  const [totalPages, setTotalPages] = React.useState(1);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);

  const load = React.useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await sdk.merchant.getWalletTransactions({
        page,
        pageSize: LEDGER_PAGE_SIZE,
      });
      setItems(result.items);
      setTotalPages(result.meta.totalPages);
    } catch (loadError) {
      setError(describeSdkError(loadError).description);
    } finally {
      setLoading(false);
    }
  }, [page]);

  React.useEffect(() => {
    void load();
  }, [load]);

  return (
    <Card>
      <CardHeader>
        <CardTitle>Ledger history</CardTitle>
        <p className="text-muted-foreground text-sm">
          Every credit and debit to your wallet — settlements, reversals, and any other adjustment.
        </p>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        {error ? (
          <p className="text-destructive text-sm" role="alert">
            {error}
          </p>
        ) : null}

        {loading && items.length === 0 ? (
          <div className="flex justify-center py-8">
            <LoadingSpinner />
          </div>
        ) : items.length === 0 ? (
          <EmptyState
            title="No ledger entries yet"
            description="Wallet activity will appear here as settlements and adjustments happen."
          />
        ) : (
          <div className="border-border/70 divide-border/70 divide-y overflow-hidden rounded-lg border">
            {items.map((entry) => (
              <div
                key={entry.id}
                className="flex items-center justify-between gap-4 px-4 py-3 text-sm"
              >
                <div className="min-w-0">
                  <p className="truncate font-medium">{entry.description ?? entry.type}</p>
                  <p className="text-muted-foreground mt-0.5 text-xs">
                    {formatDate(entry.createdAt)}
                  </p>
                </div>
                <div className="shrink-0 text-right">
                  <p className={entry.direction === 'CREDIT' ? 'text-success' : 'text-destructive'}>
                    {entry.direction === 'CREDIT' ? '+' : '-'}
                    {formatMoney(entry.amount, currency)}
                  </p>
                  <p className="text-muted-foreground text-xs">
                    Balance {formatMoney(entry.balanceAfter, currency)}
                  </p>
                </div>
              </div>
            ))}
          </div>
        )}

        <Pagination page={page} totalPages={totalPages} onChange={setPage} />
      </CardContent>
    </Card>
  );
}

/**
 * DPX-COMMERCIAL-001 Slice 5 — commercial ledger/history, mirrors
 * `LedgerCard` above exactly, backed by
 * `GET /merchant/commercial/ledger` instead of the Wallet ledger.
 */
function CommercialLedgerCard({ currency }: { currency: string }): React.JSX.Element {
  const [items, setItems] = React.useState<CommissionLedgerEntryDto[]>([]);
  const [page, setPage] = React.useState(1);
  const [totalPages, setTotalPages] = React.useState(1);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);

  const load = React.useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await sdk.commercial.listLedger({
        page,
        pageSize: COMMERCIAL_LEDGER_PAGE_SIZE,
      });
      setItems(result.items);
      setTotalPages(result.meta.totalPages);
    } catch (loadError) {
      setError(describeSdkError(loadError).description);
    } finally {
      setLoading(false);
    }
  }, [page]);

  React.useEffect(() => {
    void load();
  }, [load]);

  return (
    <Card>
      <CardHeader>
        <CardTitle>Commission ledger</CardTitle>
        <p className="text-muted-foreground text-sm">
          Every commission accrual and payment recorded against your commercial account.
        </p>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        {error ? (
          <p className="text-destructive text-sm" role="alert">
            {error}
          </p>
        ) : null}

        {loading && items.length === 0 ? (
          <div className="flex justify-center py-8">
            <LoadingSpinner />
          </div>
        ) : items.length === 0 ? (
          <EmptyState
            title="No commission activity yet"
            description="Accruals and payments against your commission account will appear here."
          />
        ) : (
          <div className="border-border/70 divide-border/70 divide-y overflow-hidden rounded-lg border">
            {items.map((entry) => (
              <div
                key={entry.id}
                className="flex items-center justify-between gap-4 px-4 py-3 text-sm"
              >
                <div className="min-w-0">
                  <p className="truncate font-medium">
                    {entry.description ?? COMMISSION_ENTRY_TYPE_LABEL[entry.type]}
                  </p>
                  <p className="text-muted-foreground mt-0.5 text-xs">
                    {formatDate(entry.createdAt)}
                  </p>
                </div>
                <div className="shrink-0 text-right">
                  <p className={entry.type === 'ACCRUAL' ? 'text-destructive' : 'text-success'}>
                    {entry.type === 'ACCRUAL' ? '+' : '-'}
                    {formatMoney(entry.amount, currency)}
                  </p>
                  <p className="text-muted-foreground text-xs">
                    Balance {formatMoney(entry.balanceAfter, currency)}
                  </p>
                </div>
              </div>
            ))}
          </div>
        )}

        <Pagination page={page} totalPages={totalPages} onChange={setPage} />
      </CardContent>
    </Card>
  );
}

function Pagination({
  page,
  totalPages,
  onChange,
}: {
  page: number;
  totalPages: number;
  onChange: (page: number) => void;
}): React.JSX.Element | null {
  if (totalPages <= 1) {
    return null;
  }
  return (
    <div className="flex items-center justify-between">
      <Button
        type="button"
        variant="outline"
        size="sm"
        disabled={page <= 1}
        onClick={() => {
          onChange(Math.max(1, page - 1));
        }}
      >
        Previous
      </Button>
      <span className="text-muted-foreground text-sm">
        Page {page} of {totalPages}
      </span>
      <Button
        type="button"
        variant="outline"
        size="sm"
        disabled={page >= totalPages}
        onClick={() => {
          onChange(Math.min(totalPages, page + 1));
        }}
      >
        Next
      </Button>
    </div>
  );
}

function BankAccountsCard(): React.JSX.Element {
  const [accounts, setAccounts] = React.useState<BankAccountDto[] | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);
  const [showForm, setShowForm] = React.useState(false);
  const [busyId, setBusyId] = React.useState<string | null>(null);

  const load = React.useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await sdk.merchant.listBankAccounts();
      setAccounts(result);
    } catch (loadError) {
      setError(describeSdkError(loadError).description);
    } finally {
      setLoading(false);
    }
  }, []);

  React.useEffect(() => {
    void load();
  }, [load]);

  const setDefault = async (id: string): Promise<void> => {
    if (busyId) {
      return;
    }
    setBusyId(id);
    setError(null);
    try {
      const updated = await sdk.merchant.setDefaultBankAccount(id);
      setAccounts((current) =>
        (current ?? []).map((account) =>
          account.id === updated.id
            ? updated
            : { ...account, isDefault: account.isDefault ? false : account.isDefault },
        ),
      );
    } catch (setDefaultError) {
      setError(describeSdkError(setDefaultError).description);
    } finally {
      setBusyId(null);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Bank account</CardTitle>
        <p className="text-muted-foreground text-sm">
          Your default bank account is the settlement destination DrippleX pays out to. Adding a
          bank account here does not start a withdrawal — DrippleX does not yet support automated
          bank payouts from the wallet.
        </p>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        {error ? (
          <p className="text-destructive text-sm" role="alert">
            {error}
          </p>
        ) : null}

        {loading ? (
          <div className="flex justify-center py-8">
            <LoadingSpinner />
          </div>
        ) : !accounts || accounts.length === 0 ? (
          <EmptyState
            title="No bank account on file"
            description="Add a bank account so your settlement destination is on record."
          />
        ) : (
          <div className="border-border/70 divide-border/70 divide-y overflow-hidden rounded-lg border">
            {accounts.map((account) => (
              <div
                key={account.id}
                className="flex flex-wrap items-center justify-between gap-3 px-4 py-3"
              >
                <div>
                  <div className="flex items-center gap-2">
                    <p className="text-sm font-medium">{account.accountName}</p>
                    {account.isDefault ? (
                      <Badge variant="success">Settlement destination</Badge>
                    ) : null}
                    {account.verifiedAt ? (
                      <Badge variant="outline">Verified</Badge>
                    ) : (
                      <Badge variant="accent">Unverified</Badge>
                    )}
                  </div>
                  <p className="text-muted-foreground mt-0.5 text-xs">
                    {account.bankName} · {account.accountNumber}
                  </p>
                </div>
                {!account.isDefault ? (
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    disabled={busyId === account.id}
                    onClick={() => {
                      void setDefault(account.id);
                    }}
                  >
                    {busyId === account.id ? 'Setting…' : 'Set as settlement destination'}
                  </Button>
                ) : null}
              </div>
            ))}
          </div>
        )}

        {showForm ? (
          <AddBankAccountForm
            onCancel={() => {
              setShowForm(false);
            }}
            onCreated={(account) => {
              setAccounts((current) => [...(current ?? []), account]);
              setShowForm(false);
            }}
          />
        ) : (
          <div>
            <Button
              type="button"
              variant="outline"
              onClick={() => {
                setShowForm(true);
              }}
            >
              Add bank account
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function AddBankAccountForm({
  onCancel,
  onCreated,
}: {
  onCancel: () => void;
  onCreated: (account: BankAccountDto) => void;
}): React.JSX.Element {
  const [banks, setBanks] = React.useState<BankOptionDto[]>([]);
  const [bankCode, setBankCode] = React.useState('');
  const [accountNumber, setAccountNumber] = React.useState('');
  // The bank's answer. Nothing is saved until it has one.
  const [resolved, setResolved] = React.useState<ResolvedBankAccountDto | null>(null);
  const [resolving, setResolving] = React.useState(false);
  const [saving, setSaving] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  // The provider's own list. A typed bank name does not match what the provider
  // calls that bank, and a settlement destination that cannot be matched is a
  // merchant who quietly never gets paid.
  React.useEffect(() => {
    void sdk.merchant
      .listBanks()
      .then(setBanks)
      .catch(() => {
        // Leave it empty rather than offering a guessed list; the form below
        // cannot be submitted without a chosen bank.
      });
  }, []);

  /**
   * Ask the bank once there is a bank and ten digits. The settlement account
   * name is whatever it returns, shown for confirmation rather than typed —
   * a transposed digit is a valid-looking number belonging to somebody else.
   */
  React.useEffect(() => {
    setResolved(null);
    if (bankCode === '' || !/^[0-9]{10}$/.test(accountNumber)) {
      return;
    }

    let abandoned = false;
    setResolving(true);
    void sdk.merchant
      .resolveBankAccount(bankCode, accountNumber)
      .then((r) => {
        if (!abandoned) {
          setResolved(r);
        }
      })
      .catch((resolveError: unknown) => {
        if (!abandoned) {
          setError(describeSdkError(resolveError).description);
        }
      })
      .finally(() => {
        if (!abandoned) {
          setResolving(false);
        }
      });

    // Still typing: a stale answer must not present the wrong name as confirmed.
    return () => {
      abandoned = true;
    };
  }, [bankCode, accountNumber]);

  const onSubmit: React.SubmitEventHandler<HTMLFormElement> = (event) => {
    event.preventDefault();
    if (saving) {
      return;
    }
    void (async () => {
      setSaving(true);
      setError(null);
      try {
        const account = await sdk.merchant.createBankAccount({
          // Both taken from the chosen option, so the name is the provider's
          // spelling rather than anyone's typing.
          // All of it confirmed by the bank, none of it typed.
          bankName: resolved?.bankName ?? '',
          bankCode,
          accountName: resolved?.accountName ?? '',
          accountNumber: accountNumber.trim(),
        });
        onCreated(account);
      } catch (submitError) {
        setError(describeSdkError(submitError).description);
      } finally {
        setSaving(false);
      }
    })();
  };

  return (
    <form
      className="border-border/70 flex flex-col gap-4 rounded-lg border p-4"
      onSubmit={onSubmit}
    >
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="bankCode">Bank</Label>
          <select
            id="bankCode"
            required
            className="border-input bg-background h-9 rounded-md border px-3 py-1 text-sm"
            value={bankCode}
            onChange={(event) => {
              setBankCode(event.target.value);
            }}
          >
            <option value="">{banks.length === 0 ? 'Loading banks…' : 'Choose your bank'}</option>
            {banks.map((bank) => (
              <option key={bank.code} value={bank.code}>
                {bank.name}
              </option>
            ))}
          </select>
        </div>
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="accountName">Account name</Label>
          {/* Read-only on purpose: this is the bank's answer, not an input. */}
          <Input
            id="accountName"
            readOnly
            value={
              resolving
                ? 'Checking with the bank…'
                : (resolved?.accountName ?? 'Choose a bank and enter the account number')
            }
            className={resolved === null ? 'text-muted-foreground' : undefined}
          />
        </div>
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="accountNumber">Account number</Label>
          <Input
            id="accountNumber"
            required
            minLength={10}
            maxLength={10}
            inputMode="numeric"
            value={accountNumber}
            onChange={(event) => {
              setAccountNumber(event.target.value);
            }}
          />
        </div>
      </div>

      {error ? (
        <p className="text-destructive text-sm" role="alert">
          {error}
        </p>
      ) : null}

      <div className="flex justify-end gap-2">
        <Button type="button" variant="outline" onClick={onCancel} disabled={saving}>
          Cancel
        </Button>
        <Button type="submit" disabled={saving}>
          {saving ? 'Saving…' : 'Add account'}
        </Button>
      </div>
    </form>
  );
}
