export interface PermissionSeed {
  code: string;
  description: string;
}

export const PERMISSION_SEEDS: PermissionSeed[] = [
  { code: 'profile:read', description: 'Read own profile' },
  { code: 'profile:write', description: 'Update own profile' },
  { code: 'auth:sessions:read', description: 'List own auth sessions' },
  { code: 'auth:sessions:revoke', description: 'Revoke own auth sessions' },
  { code: 'customer:addresses:manage', description: 'Manage customer addresses' },
  { code: 'admin:addresses:read', description: 'Read customer addresses (admin)' },
  { code: 'customer:cart:manage', description: 'Manage own shopping cart' },
  { code: 'admin:cart:read', description: 'Read shopping carts (admin)' },
  { code: 'customer:checkout', description: 'Create orders from shopping cart' },
  { code: 'customer:orders', description: 'View and cancel own orders' },
  { code: 'admin:orders:read', description: 'Read orders (admin)' },
  { code: 'customer:delivery:read', description: 'Read own delivery jobs and tracking' },
  { code: 'rider:delivery:manage', description: 'Manage assigned delivery jobs' },
  { code: 'admin:delivery:manage', description: 'Manage delivery jobs (admin)' },
  { code: 'merchant:onboarding:submit', description: 'Submit merchant onboarding' },
  { code: 'merchant:onboarding:approve', description: 'Approve merchant onboarding' },
  { code: 'merchant:business:manage', description: 'Manage own merchant business profile' },
  { code: 'merchant:kyc:manage', description: 'Manage own merchant KYC documents' },
  { code: 'merchant:bank:manage', description: 'Manage own merchant bank accounts' },
  { code: 'admin:merchants:review', description: 'Review merchant onboarding applications' },
  { code: 'admin:merchants:approve', description: 'Approve merchants' },
  { code: 'admin:merchants:reject', description: 'Reject merchants' },
  { code: 'admin:merchants:suspend', description: 'Suspend merchants' },
  { code: 'admin:merchants:reactivate', description: 'Reactivate suspended merchants' },
  { code: 'rider:onboarding:submit', description: 'Submit rider onboarding' },
  { code: 'rider:onboarding:approve', description: 'Approve rider onboarding' },
  { code: 'driver:onboarding:submit', description: 'Submit driver onboarding' },
  { code: 'driver:onboarding:approve', description: 'Approve driver onboarding' },
  { code: 'users:read', description: 'Read user records' },
  { code: 'users:write', description: 'Update user records' },
  { code: 'users:delete', description: 'Soft-delete user records' },
  { code: 'users:roles:assign', description: 'Assign or remove user roles' },
  { code: 'roles:read', description: 'Read roles' },
  { code: 'roles:write', description: 'Create and update roles' },
  { code: 'permissions:read', description: 'Read permissions catalog' },
  { code: 'audit:read', description: 'Read audit logs' },
  { code: 'platform:settings:write', description: 'Update platform settings' },
];
