export const ROLE_PERMISSION_GRANTS: Record<string, string[]> = {
  customer: [
    'profile:read',
    'profile:write',
    'auth:sessions:read',
    'auth:sessions:revoke',
    'customer:addresses:manage',
  ],
  merchant: [
    'profile:read',
    'profile:write',
    'auth:sessions:read',
    'auth:sessions:revoke',
    'merchant:onboarding:submit',
  ],
  rider: [
    'profile:read',
    'profile:write',
    'auth:sessions:read',
    'auth:sessions:revoke',
    'rider:onboarding:submit',
  ],
  driver: [
    'profile:read',
    'profile:write',
    'auth:sessions:read',
    'auth:sessions:revoke',
    'driver:onboarding:submit',
  ],
  operations_staff: [
    'profile:read',
    'profile:write',
    'auth:sessions:read',
    'auth:sessions:revoke',
    'merchant:onboarding:approve',
    'rider:onboarding:approve',
    'driver:onboarding:approve',
    'users:read',
    'audit:read',
  ],
  administrator: [
    'profile:read',
    'profile:write',
    'auth:sessions:read',
    'auth:sessions:revoke',
    'merchant:onboarding:approve',
    'rider:onboarding:approve',
    'driver:onboarding:approve',
    'users:read',
    'users:write',
    'users:delete',
    'users:roles:assign',
    'roles:read',
    'permissions:read',
    'audit:read',
  ],
  super_administrator: [
    'profile:read',
    'profile:write',
    'auth:sessions:read',
    'auth:sessions:revoke',
    'customer:addresses:manage',
    'merchant:onboarding:submit',
    'merchant:onboarding:approve',
    'rider:onboarding:submit',
    'rider:onboarding:approve',
    'driver:onboarding:submit',
    'driver:onboarding:approve',
    'users:read',
    'users:write',
    'users:delete',
    'users:roles:assign',
    'roles:read',
    'roles:write',
    'permissions:read',
    'audit:read',
    'platform:settings:write',
  ],
};
