{
 "title": "Dripplex Database",
 "tags": [
  "dripplex",
  "d3"
 ],
 "panels": [
  {
   "title": "PG up",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pg_up" }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 0 },
   "targets": [
    { "expr": "pg_stat_activity_count" }
   ]
  },
  {
   "title": "Database size bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pg_database_size_bytes" }
   ]
  }
 ]
}