// RIDE OPERATIONS CONSOLE — DrippleX Admin (desktop-first)
export {
  AdminConsoleScreen,
  AdminDashboardScreen,
  AdminLiveMapScreen,
  AdminTripsScreen,
  AdminDriversScreen,
  AdminKYCScreen,
  AdminVehiclesScreen,
  AdminCustomersScreen,
  AdminCampaignsScreen,
  AdminReferralsScreen,
  AdminReferralReviewScreen,
  AdminReferralProgrammesScreen,
  AdminDxPointsScreen,
  AdminPricingScreen,
  AdminIncidentsScreen,
  AdminSupportScreen,
  AdminAnalyticsScreen,
  AdminReportsScreen,
  AdminSettingsScreen,
  AdminAuditScreen,
  AdminProfileScreen,
} from '../../app/adminConsoleScreen';
