ALTER TYPE "NotificationType" ADD VALUE 'ORDER_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE 'ORDER_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'ORDER_READY';
ALTER TYPE "NotificationType" ADD VALUE 'ORDER_DELAYED';
ALTER TYPE "NotificationType" ADD VALUE 'ORDER_COMPLETED';
