import {
  isSyntheticEmail,
  makeSyntheticEmail,
  SYNTHETIC_EMAIL_DOMAIN,
} from './synthetic-email.util';

describe('synthetic-email.util', () => {
  describe('makeSyntheticEmail', () => {
    it('derives a deterministic placeholder from the phone digits', () => {
      expect(makeSyntheticEmail('+2348012345678')).toBe(`2348012345678@${SYNTHETIC_EMAIL_DOMAIN}`);
    });

    it('strips non-digit characters before building the address', () => {
      expect(makeSyntheticEmail('+234 801 234 5678')).toBe(
        `2348012345678@${SYNTHETIC_EMAIL_DOMAIN}`,
      );
    });

    it('is deterministic for the same phone number', () => {
      expect(makeSyntheticEmail('+2348012345678')).toBe(makeSyntheticEmail('+2348012345678'));
    });
  });

  describe('isSyntheticEmail', () => {
    it('recognises an address generated by makeSyntheticEmail', () => {
      expect(isSyntheticEmail(makeSyntheticEmail('+2348012345678'))).toBe(true);
    });

    it('is case-insensitive', () => {
      expect(isSyntheticEmail(`2348012345678@${SYNTHETIC_EMAIL_DOMAIN.toUpperCase()}`)).toBe(true);
    });

    it('rejects a real email address', () => {
      expect(isSyntheticEmail('ada@example.com')).toBe(false);
    });

    it('rejects an address that merely contains the domain as a substring', () => {
      expect(isSyntheticEmail(`user@evil.com/${SYNTHETIC_EMAIL_DOMAIN}`)).toBe(false);
    });
  });
});
